# Generated by Django 4.2.16 on 2024-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('registro_cnh', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
            ],
        ),
    ]
